server:
  port: 8080
spring:
  profiles:
    active: test

  application:
    name: spring-boot-jpa-hikari

  thymeleaf:
    #开启MVC thymeleaf 视图解析
    enabled: true
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML

  mvc:
    ##多余的配置，默认就会扫描static
    static-path-pattern: /static/**
    #表单时间
    dateFormat: yyyy-MM-dd HH:mm:ss

    ###配置输出输入时间
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
#      #  resources:
#      static-locations: classpath:/static/
  jpa:
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5
##开始日志
#logging:
#  level:
#    com.hunmengwl.oauth: debug